name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  MC_EMAIL: ${{ secrets.MC_EMAIL }}
  MC_PASSWORD: ${{ secrets.MC_PASSWORD }}
  MC_TOTP_SECRET: ${{ secrets.MC_TOTP_SECRET }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
