name: Rust

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      env:
        CARGO_TERM_COLOR: always
        MC_EMAIL: ${{ secrets.MC_EMAIL }}
        MC_PASSWORD: ${{ secrets.MC_PASSWORD }}
        MC_TOTP_SECRET: ${{ secrets.MC_TOTP_SECRET }}
        RUSTFLAGS: "-Cinstrument-coverage"
      run: cargo test --verbose
    - name: Run coverage
      env:
        LLVM_PROFILE_FILE: "bombay-%p-%m.profraw"
      run: |
        rustup component add llvm-tools-preview 
        curl -L https://github.com/mozilla/grcov/releases/latest/download/grcov-x86_64-unknown-linux-gnu.tar.bz2 | tar jxf -
        ./grcov . --binary-path ./target/debug -s . -t lcov --branch --ignore-not-existing --ignore "../*" --ignore "/*" -o cov.lcov
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
